# Generated by Django 6.0 on 2026-02-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gamedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Multipl', 'Multiplayer'), ('RPG', 'Action RPG'), ('Racing', 'Racing'), ('Rogue', 'Rogue'), ('Sim', 'Simulator'), ('online', 'Online Co-op'), ('Horror', 'Horror'), ('Indie', 'Indie'), ('AAA', 'AAA Titles')], max_length=10)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('game_price', models.IntegerField()),
                ('game_image', models.ImageField(upload_to='game_image/')),
                ('game_logo', models.ImageField(blank=True, null=True, upload_to='games/logos/')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='games/screenshots/')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='games/screenshots/')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='games/screenshots/')),
                ('screenshot4', models.ImageField(blank=True, null=True, upload_to='games/screenshots/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='games/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profiles/default.png', upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gamedetails')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gamedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
