# Generated by Django 6.0 on 2026-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discription_petdetails_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Multipl', 'Multiplayer'), ('RPG', 'Action RPG'), ('Racing', 'Racing'), ('Rogue', 'Rogue'), ('Sim', 'Simulator'), ('online', 'Online Co-op'), ('Horror', 'Horror'), ('Indie', 'Indie'), ('AAA', 'AAA Titles')], max_length=10)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('game_price', models.IntegerField()),
                ('game_image', models.ImageField(upload_to='game_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='petdetails',
        ),
    ]
