# Generated by Django 6.0 on 2026-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gamedetails_delete_petdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='game_logo',
            field=models.ImageField(blank=True, null=True, upload_to='games/logos/'),
        ),
    ]
