# Generated by Django 6.0 on 2026-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
