# Generated by Django 6.0 on 2026-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gamedetails_game_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='games/videos/'),
        ),
    ]
