# Generated by Django 6.0 on 2026-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gamedetails_screenshot1_gamedetails_screenshot2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='screenshot4',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
    ]
