# Generated by Django 6.0 on 2026-01-21 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'game')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
